git:
  depth: 5

addons:
  apt:
    packages:
      - libcurl4-openssl-dev # required to avoid SSL errors
      - openjdk-8-jre

language: node_js

node_js:
  - "10"

env:
  global:
    - RUBY_VERSION=2.4

before_install:
  - export NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - rvm use $RUBY_VERSION --install --binary --fuzzy

install:
  - npm ci
  - bundle install --deployment --jobs=3 --retry=3 --clean

script:
  - bundle exec jekyll build
  - bundle exec htmlproofer _site/ --check-external-hash --check-favicon --check-img-http --check-opengraph --empty-alt-ignore --enforce-https --internal-domains sustainoss.org
  - npm test

matrix:
  fast_finish: true

cache:
  directories:
    - "$HOME/.npm"
    - vendor/bundle

notifications:
  email: false
